/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Bus;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-05-30T00:10:05.092Z")

@Api(value = "bus", description = "the bus API")
@RequestMapping(value = "/v2")
public interface BusApi {

    @ApiOperation(value = "Add a new Bus", nickname = "addBus", notes = "", tags={ "Bus", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/bus",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addBus(@ApiParam(value = "Bus object that needs to be add" ,required=true )  @Valid @RequestBody Bus body);


    @ApiOperation(value = "Deletes a  Bus", nickname = "deleteBus", notes = "", tags={ "Bus", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid object"),
        @ApiResponse(code = 404, message = "Bus not found") })
    @RequestMapping(value = "/bus",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteBus(@ApiParam(value = "Bus object that needs to be deleted" ,required=true )  @Valid @RequestBody Bus body);


    @ApiOperation(value = "Find all bus", nickname = "findAll", notes = "Return All the Bus from the system", response = Bus.class, responseContainer = "List", tags={ "Bus", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Bus.class, responseContainer = "List") })
    @RequestMapping(value = "/bus",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Bus>> findAll();


    @ApiOperation(value = "Finds Bus by Bus Number", nickname = "findBusByBusNumber", notes = "", response = Bus.class, tags={ "Bus", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Bus.class),
        @ApiResponse(code = 400, message = "Invalid Bus Number") })
    @RequestMapping(value = "/bus/{busNumber}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Bus> findBusByBusNumber(@ApiParam(value = " Bus Number that need to be considered for filter",required=true) @PathVariable("busNumber") String busNumber);


    @ApiOperation(value = "Update an existing Bus", nickname = "updateBus", notes = "Modify the existing Bus", tags={ "Bus", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Bus not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/bus",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateBus(@ApiParam(value = "Bus object that needs to be added" ,required=true )  @Valid @RequestBody Bus body);

}
